<!DOCTYPE html>
<html>
<head>
    <title>iWantBut</title>
        <!-- Latest compiled and minified CSS & JS -->
    <!-- <script src="//code.jquery.com/jquery.js"></script> -->
    <!-- <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script> -->
    <!-- <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css"> -->
    <link rel="stylesheet" type="text/css" href="public/assets/css/global.css">
</head>
<header>
    <!--  -->
</header>