<style>
/** Polymer Script END **/

body {
  padding: 0;
  margin: 0;
  -webkit-transform: translateZ(0);
  transform: translateZ(0);
}
section {
  font-family: RobotoDraft, 'Helvetica Neue', Helvetica, Arial;
  font-size: 16px;
  text-align: center;
  padding: 36px 20%;
  background: #eee;
}
paper-input {
  width: 100%;
  text-align: left;
}
.dark-theme {
  background: #333333;
  color: #ccc;
}
.dark-theme paper-input {
  color: #666;
}
.dark-theme input {
  color: #fff;
}
.dark-theme /deep/ input {
  color: #fff;
}
.dark-theme #underline {
  background: #666;
  border-bottom-color: #666;
}
.dark-theme /deep/ #underline {
  background: #666;
  border-bottom-color: #666;
}
.dark-theme .focusedColor {
  color: #7d8ad0;
  background: #7d8ad0;
}
.dark-theme /deep/ .focusedColor {
  color: #7d8ad0;
  background: #7d8ad0;
}
/** Polymer Script END **/

</style>