<!DOCTYPE html>
<html lang="en" class="<?php print $class; ?>">

<head>
	<title><?php print $title; ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<?php if(isset($meta) && is_array($meta)): ?>
    <?php foreach($meta as $name => $content): ?>
    <meta name="<?php print $name; ?>" content="<?php print $content; ?>" />
    <?php endforeach; ?>
    <?php endif; ?>

    <style type="text/css">
    </style>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="assets/front/public/stylesheet/bootstrap.min.css">
	<!-- Optional theme -->
	<link rel="stylesheet" href="assets/front/public/stylesheet/bootstrap-theme.min.css">
	<!-- Main Page style -->
    <link rel="stylesheet" type="text/css" media="screen" href="/assets/front/public/stylesheet/style.css" />

    <link rel="stylesheet" type="text/css" href="assets/front/public/stylesheet/default.css" />
    <link rel="stylesheet" type="text/css" href="assets/front/public/stylesheet/component.css" />
</head>

<body>
	<div class="page">
		<div class="head"><?php echo $head; ?></div>
		<div class="body"><?php echo $body; ?></div>
		<!-- <div class="foot"><?php echo $foot; ?></div> -->
		<script type="text/javascript" src="/assets/front/public/scripts/script.js"></script>
        <script src="/assets/front/public/platform/platform.js"></script>

        <link href="/assets/front/public/font-roboto/roboto.html" rel="import">
        <link href="/assets/front/public/paper-input.html" rel="import">
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="/assets/front/public/scripts/jquery.js"></script>
    <!-- Latest compiled and minified JavaScript -->
	<script src="/assets/front/public/scripts/bootstrap.min.js"></script>

</body>
</html>