<body class="nl-blurred">
    <div class="container demo-1">
      <!-- Top Navigation -->
      <header>
        <h1>iWantBut.com<span></span></h1>
        <h2>Having trouble choosing what to buy? compare it now<span></span></h2>
      </header>
      <div class="main clearfix">
        <form id="nl-form" class="nl-form" method="POST" action="/result">
          I want to buy
           <input type="text" name="iWant" class="" placeholder="..." required/><br />  but
          I also<br /> like
          <input type="text" class=""  name="iLike" placeholder="..." required/>
          <div class="nl-submit-wrap">
            <button class="nl-submit" type="submit">Compare my desires</button>
          </div>
          <div class="nl-overlay"></div>
        </form>
      </div>
    </div><!-- /container -->
  </body>