<body>
<div class="container">
    <div class="row">
      <div class="col-xs-12 col-lg-12"><img src="assets/front/public/images/iwantbut-logo.jpg" alt="..." class="img-circle"></div>
    </div>
    <form class="form-horizontal" role="form" method="POST" action="/result">
      <div class="form-group">
        <div class="col-lg-12">
            <input type="text" name="iWant" class="input-text-home form-control" placeholder="I WANT A ..." required/>
        </div>
      </div>
        <div class="form-group">
        <div class="col-lg-12">
            <input type="text" name="iLike" class="input-text-home form-control" placeholder="BUT I LIKE ..." required/>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-12">
            <input type="submit" name="submit" class="form-control" />
        </div>
      </div>
    </form>
</div>
</body>
</html>